### DISCUSSION TITLE
How to better organise CSS code

### DISCUSSION THREAD

**Discussion by f14m07** [liedekef/events-made-easy#654] [General]
Hi,
I have CSS code for EME pages in several places:
1- in the Additional CSS part of my child theme Twenty Twenty Four, which also contains CSS code for WP
2- in the two files eme.css and eme_print.css, in my theme directory, to manage the display and printing of #_EVENTPRINTBOOKINGSLINK

Is it possible to improve and simplify this all this? In particular, the additional CSS part of the theme is not very user-friendly

**Comment by liedekef** [comment]
I can't help how WP works :-) But you can put all your extra css in the eme.css file, doesn't that work?
Also, see the setting "Extra html header" setting in EME.

**Comment by f14m07** [comment]
Thanks I will test

**Comment by f14m07** [comment]
Yes, everything can be put in eme.css
I suppose that the benefits of using ‘Extra html header’ are :
- reduce the length of the eme.css file
- only load CSS on certain event or location pages
But perhaps there are limits?
Can I just put the CS there?

**Reply by liedekef** [reply]
Well, a separate file (like eme.css) has the advantage of being cached by the browser, so it is faster.
But you can put it in the header setting (but: wordpress might filter stuff out in there, so check the result after saving it). Next to that: you have a setting for headers per event/location too.

**Comment by f14m07** [comment]
It seems that the WP CSS code for my child block theme is not taken into account if it is in eme.css, for example for the menu. Only EME CSS code is Ok.
I have to put it in the additional CSS tab when I edit the theme

**Reply by liedekef** [reply]
did you enclose it in a style-tag? When I test it here, the theme CSS loads before the extra EME css ...

**Comment by f14m07** [comment]
For example, this CSS doesn't work in eme.css
```css
/* Styles for WP menu all items */
.wp-block-navigation .wp-block-navigation-item__content {
    font-size: 17px;
    margin-right : 10px;
    padding-right: 10px;
    color: Black;
    background-color: azure;
}
.wp-block-navigation .wp-block-navigation-item__content:hover {
    color: blue;
    background-color: LightGreen;
}

/* styles specifically for WP sub menu items */
.wp-block-navigation__submenu-container .wp-block-navigation-item__content {
    font-size: 15px;
    color: Black;
    background-color: azure;
}
.wp-block-navigation__submenu-container .wp-block-navigation-item__content:hover {
    color: blue;
    background-color: LightGreen;
}
.wp-block-buttons>.wp-block-button.wp-block-button__width-100 {
    flex-basis: 70%;
    width: 80%;
}
```
It aplies to the block navigation
